### ISSUE TITLE
Test suite fails

### ISSUE THREAD

**Issue by eserte** [uperl/Test2-Tools-Rustfmt#3]
The test suite fails on all of my smokers, but also on other people's systems (e.g. from ANDK). A sample fail report:
http://www.cpantesters.org/cpan/report/b2982722-5469-11ed-90a5-e05360ca80ec

**Comment by plicease** [comment]
Ah thanks for the report.  It is supposed to `exit 0` from Makefile.PL if you do not have rustfmt, but I forgot to wire the script that does that into the Makefile.PL.

**Comment by plicease** [comment]
This should be fixed in 0.03 thanks again!
